const colors = {
  light: {
    text: "#0C1221",
    tint: "#00CFFF",
    background: "#F0F4FA",
    foreground: "#0C1221",
    card: "#FFFFFF",
    cardForeground: "#0C1221",
    primary: "#0066FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F0FF",
    secondaryForeground: "#0C1221",
    muted: "#EEF2F8",
    mutedForeground: "#6B7FA3",
    accent: "#7B61FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#DDE4F0",
    input: "#DDE4F0",
    success: "#00C67A",
    warning: "#FFB300",
    screenTimeColor: "#0066FF",
    healthColor: "#00C67A",
    calendarColor: "#7B61FF",
    trendsColor: "#FF6B6B",
    socialColor: "#FF6B6B",
    productivityColor: "#0066FF",
    entertainmentColor: "#7B61FF",
    communicationColor: "#00C67A",
    otherColor: "#FFB300",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00CFFF",
    background: "#0C1221",
    foreground: "#FFFFFF",
    card: "#141E35",
    cardForeground: "#FFFFFF",
    primary: "#00CFFF",
    primaryForeground: "#0C1221",
    secondary: "#1A2740",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2740",
    mutedForeground: "#7B9CC4",
    accent: "#7B61FF",
    accentForeground: "#FFFFFF",
    destructive: "#FF5252",
    destructiveForeground: "#FFFFFF",
    border: "#1E3050",
    input: "#1E3050",
    success: "#00E676",
    warning: "#FFB300",
    screenTimeColor: "#00CFFF",
    healthColor: "#00E676",
    calendarColor: "#7B61FF",
    trendsColor: "#FF6B6B",
    socialColor: "#FF6B6B",
    productivityColor: "#00CFFF",
    entertainmentColor: "#7B61FF",
    communicationColor: "#00E676",
    otherColor: "#FFB300",
  },
  radius: 16,
};

export default colors;
